//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dafcam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bit
    {
        public int ID { get; set; }
        public double ShaftDiameter { get; set; }
        public double OuterDiameter { get; set; }
        public double Length { get; set; }
        public long Worktime { get; set; }
        public string IntStallsAt { get; set; }
        public string IntDropsAt { get; set; }
        public string Name { get; set; }
    }
}
