//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dafcam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DafcamEntities : DbContext
    {
        public DafcamEntities()
            : base("name=DafcamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Axis> Axes { get; set; }
        public DbSet<Bit> Bits { get; set; }
        public DbSet<Controller> Controllers { get; set; }
        public DbSet<Motor> Motors { get; set; }
        public DbSet<Spindle> Spindles { get; set; }
    }
}
