//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dafcam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motor
    {
        public int ID { get; set; }
        public int AxisID { get; set; }
        public decimal ShortDistance { get; set; }
        public decimal Position { get; set; }
        public bool UseRamping { get; set; }
        public int MaxRpm { get; set; }
        public int DwellRpm { get; set; }
        public int CurrentRpm { get; set; }
        public string Name { get; set; }
        public int AccelerationStartsAt { get; set; }
    
        public virtual Axis Axis { get; set; }
    }
}
