//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dafcam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spindle
    {
        public int ID { get; set; }
        public int TargetRpm { get; set; }
        public int CurrentRpm { get; set; }
        public Nullable<int> CurrentBitID { get; set; }
        public Nullable<int> TargetBitID { get; set; }
        public string Name { get; set; }
    
        public virtual Bit CurrentBit { get; set; }
        public virtual Bit TargetBit { get; set; }
    }
}
